$LOAD_PATH << File.expand_path(File.dirname(__FILE__))
require 'rubygems'
require 'colorize'
require 'mini_magick'

require 'core/board'
require 'core/solution'
require 'core/puzzle'
require 'core/rendered_board'
require 'pieces/piece'
require 'pieces/placed_piece'
require 'pieces/position'
require 'pieces/red_piece'
require 'pieces/blue_piece'
require 'pieces/orange_piece'
require 'pieces/purple_piece'
require 'pieces/green_piece'
require 'pieces/knight_piece'
require 'pieces/princess_piece'

